#!/bin/bash

# Instalar MySql Server 
sudo apt-get install mysql-server -y

# Instalar módulo MySql Python
sudo dpkg -i mysql-connector-python_2.0.1-1ubuntu12.04_all.deb
sudo apt-get install python-dev libmysqlclient-dev
sudo apt-get install python-mysqldb


